name: Terraform Dev

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: environments/dev
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1
  TF_VAR_environment: dev
  TF_VAR_project_name: terraform-lab


jobs:
  # Job 1: Generates the plan automatically
  terraform-plan:
    name: terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Toolchain
        uses: ./.github/actions/setup-terraform-local
        with:
          localstack-token: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Run Terraform tests
        run: |
          tflocal init -reconfigure -input=false
          tflocal test

      - name: Check LocalStack logs
        run: |
          localstack logs

      - name: Terraform format check
        run: tflocal fmt -check -recursive . ../../modules

      - name: Terraform validate
        run: tflocal validate -no-color

      - name: Terraform plan
        run: tflocal plan -input=false -no-color -lock-timeout=5m -out=tfplan

      - name: Terraform show
        run: |
          tflocal show -json tfplan > tfplan.json
          echo "| Action | Resource Type | Resource Name |"
          echo "|---|---|---|"
          jq -r '.resource_changes[] | "| \(.change.actions | join(",")) | \(.type) | \(.name) |"' tfplan.json
     
      # Save the plan file so the next job can use it
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            environments/dev/tfplan
            environments/dev/.terraform.lock.hcl



  # Job 2: Pauses and waits for manual approval
  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: terraform-dev   # <-- THIS triggers the approval prompt
    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Toolchain
        uses: ./.github/actions/setup-terraform-local
        with:
          localstack-token: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: environments/dev

      - name: Terraform Init
        run: tflocal init -input=false

      - name: Terraform apply
        run: tflocal apply -input=false -no-color tfplan





