name: Terraform Dev

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: environments/dev
  TF_IN_AUTOMATION: true
  AWS_REGION: us-east-1
  TF_VAR_environment: dev
  TF_VAR_project_name: terraform-lab


jobs:
  # Job 1: Generates the plan automatically
  terraform-plan:
    name: terraform-plan
    runs-on: ubuntu-latest
    # environment: terraform-dev
    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tflocal
        run: |
          pip install terraform-local
          pip show terraform-local

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: "latest"
          install-awslocal: "true"
          use-pro: "true"
          configuration: LS_LOG=trace
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Run Terraform tests
        run: |
          tflocal init -reconfigure -input=false
          tflocal test

      - name: Check LocalStack logs
        run: |
          localstack logs

      - name: Terraform format check
        run: tflocal fmt -check -recursive . ../../modules

      - name: Terraform validate
        run: tflocal validate -no-color

      - name: Terraform plan
        run: tflocal plan -input=false -no-color -lock-timeout=5m -out=tfplan

      # Save the plan file so the next job can use it
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  # Job 2: Pauses and waits for manual approval
  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: terraform-dev   # <-- THIS triggers the approval prompt
    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform apply
        run: tflocal apply -input=false -no-color tfplan





